# Site settings
title: Véro + John
description: sneak peek of photos from Tipsy, 31st March 2018
baseurl: "/lens_31mar18_tipsy" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
image_dir: "assets/images/1200x750/"
image_tn_dir: "assets/images/360x225/"

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/explore/tags/veroetjohn/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
